---
title: Dorawei
timezone: Asia/Hong_Kong
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
bio: "#language #type #design #acg\n#旅行 #讀書 #發呆 "
description: Hello World
reading_time: false
words_per_minute: 200
logo: assets/img/logo.png
background: assets/img/bgimg-tst.png
tiled_bg: false
locale: en_US
url: https://dorawei.xyz
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: false
sass:
  sass_dir: _sass
  style: compressed
disqus_shortname: dorawei
email: me@dorawei.xyz
github: dorawei
steam: dorawei
gems:
- jekyll-mentions
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
- kramdown-parser-gfm
jekyll-mentions:
  base_url: https://github.com
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
